#!/bin/bash
# Desc: Find out frequency of words in a file

if [ $# -ne 1 ];
then
  echo "Usage: $0 filename";
  exit 1
fi

filename=$1
egrep -o "\b[[:alpha:]]+\b" "$filename" | \
awk '{ count[$0]++ }
END {
for(ind in count)
{ printf("%d\t%s\n",count[ind],ind); }
}'
